### ISSUE TITLE
UIKeyInput instead of UITextInput

### ISSUE THREAD

**Issue by eliotfowler** [illyabusigin/CYRKeyboardButton#5]
The delegate should need to support only UIKeyInput as UITextInput requires a lot of unnecessary methods.

**Comment by illyabusigin** [comment]
Hi Eliot!

The reason I opted for `UITextInput` vs. `UIKeyInput` is because `UITextField` doesn't have a selected text range. When calling `insertText:` with CYRKeyBoardButton I wanted to be able to check the delegate for the specified range. If you have a better solution to accomplish the above while using `UIKeyInput` I'm all ears ;).
